import assert from "node:assert/strict";
import { readFile, readdir, stat } from "node:fs/promises";
import test from "node:test";

test("builds a D1-backed worker artifact", async () => {
  const hosting = JSON.parse(
    await readFile(
      new URL("../dist/.openai/hosting.json", import.meta.url),
      "utf8",
    ),
  );
  const worker = await stat(new URL("../dist/server/index.js", import.meta.url));

  assert.equal(hosting.d1, "DB");
  assert.ok(
    hosting.project_id === null || typeof hosting.project_id === "string",
  );
  assert.ok(worker.size > 0);
});

test("ships an empty blog schema", async () => {
  const migration = await readFile(
    new URL("../drizzle/0000_fast_owl.sql", import.meta.url),
    "utf8",
  );

  assert.match(migration, /CREATE TABLE `blog_posts`/);
  assert.match(migration, /DEFAULT 'planned'/);
  assert.doesNotMatch(migration, /INSERT\s+INTO/i);
});

test("has no starter identity or sample administrator", async () => {
  const [siteConfig, adminConfig, packageManifest] = await Promise.all([
    readFile(new URL("../config/site.ts", import.meta.url), "utf8"),
    readFile(new URL("../config/admin.ts", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.doesNotMatch(siteConfig, /Your Blog|example\.com/i);
  assert.doesNotMatch(adminConfig, /[\w.+-]+@[\w.-]+\.[a-z]{2,}/i);
  assert.match(adminConfig, /CMS_ADMIN_EMAILS/);
  assert.match(packageManifest, /"version": "1\.3\.2"/);
});

test("keeps source comments neutral and attribution-free", async () => {
  const root = new URL("../", import.meta.url);
  const excludedDirectories = new Set([".git", ".next", ".sites-runtime", ".wrangler", "dist", "node_modules"]);
  const sourceExtensions = new Set([".css", ".html", ".js", ".jsx", ".md", ".mjs", ".mts", ".scss", ".sh", ".ts", ".tsx", ".yaml", ".yml"]);
  const bannedLanguage = /\b(?:we|us|our|ours|you|your|yours)\b|\bas an ai\b|\b(?:chatgpt|claude|copilot)\b|\bgenerated by\b/i;

  async function collect(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    const files = [];
    for (const entry of entries) {
      if (entry.isDirectory()) {
        if (!excludedDirectories.has(entry.name)) files.push(...await collect(new URL(`${entry.name}/`, directory)));
        continue;
      }
      const extension = entry.name.slice(entry.name.lastIndexOf("."));
      if (sourceExtensions.has(extension)) files.push(new URL(entry.name, directory));
    }
    return files;
  }

  for (const file of await collect(root)) {
    const source = await readFile(file, "utf8");
    const supportsHashComments = /\.(?:sh|yaml|yml)$/.test(file.pathname);
    const comments = [
      ...(source.match(/\/\*[\s\S]*?\*\//g) || []),
      ...(source.match(/^\s*\/\/.*$/gm) || []),
      ...(source.match(/<!--[\s\S]*?-->/g) || []),
      ...(supportsHashComments ? source.match(/^\s*#(?!\!).*$/gm) || [] : []),
    ];
    for (const comment of comments) assert.doesNotMatch(comment, bannedLanguage, file.pathname);
  }
});

test("ships complete GitHub project metadata", async () => {
  const [readme, contributing, changelog, workflow, dependabot, packageManifest] = await Promise.all([
    readFile(new URL("../README.md", import.meta.url), "utf8"),
    readFile(new URL("../CONTRIBUTING.md", import.meta.url), "utf8"),
    readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8"),
    readFile(new URL("../.github/workflows/ci.yml", import.meta.url), "utf8"),
    readFile(new URL("../.github/dependabot.yml", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  assert.match(readme, /^# White Hat CMS Lite/m);
  assert.match(readme, /Production installation/);
  assert.match(contributing, /npm run lint/);
  assert.match(changelog, /\[1\.3\.2\]/);
  assert.match(workflow, /actions\/checkout@v6/);
  assert.match(workflow, /actions\/setup-node@v7/);
  assert.match(dependabot, /package-ecosystem: npm/);
  assert.match(packageManifest, /"description":/);
  assert.match(packageManifest, /"license": "MIT"/);
});

test("keeps public discovery routes and server-side authorization", async () => {
  const [robots, sitemap, feed, authorization] = await Promise.all([
    readFile(new URL("../app/robots.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/sitemap.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/feed.xml/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/blog-admin-auth.ts", import.meta.url), "utf8"),
  ]);

  assert.match(robots, /disallow: \["\/admin\/", "\/api\/"\]/);
  assert.match(sitemap, /getPublishedPosts/);
  assert.match(feed, /application\/rss\+xml/);
  assert.match(authorization, /requireAuthenticatedUser/);
});

test("ships white-label settings and public integration routes", async () => {
  const [migration, settings, appearanceRoute, postsRoute, themeRoute] =
    await Promise.all([
      readFile(
        new URL("../drizzle/0001_colorful_omega_flight.sql", import.meta.url),
        "utf8",
      ),
      readFile(new URL("../lib/site-settings.ts", import.meta.url), "utf8"),
      readFile(
        new URL("../app/api/admin/settings/route.ts", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL("../app/api/public/posts/route.ts", import.meta.url),
        "utf8",
      ),
      readFile(
        new URL("../app/api/public/theme/route.ts", import.meta.url),
        "utf8",
      ),
    ]);

  assert.match(migration, /CREATE TABLE `site_settings`/);
  assert.match(settings, /customCss/);
  assert.match(appearanceRoute, /getBlogAdmin/);
  assert.match(postsRoute, /access-control-allow-origin/);
  assert.match(themeRoute, /access-control-allow-origin/);
  assert.doesNotMatch(themeRoute, /customCss:\s*settings\.customCss/);
});

test("includes production publishing capabilities", async () => {
  const [migration, ai, media, wordpress, operations, hosting] = await Promise.all([
    readFile(new URL("../drizzle/0002_oval_skin.sql", import.meta.url), "utf8"),
    readFile(new URL("../lib/integrations.ts", import.meta.url), "utf8"),
    readFile(new URL("../lib/media.ts", import.meta.url), "utf8"),
    readFile(new URL("../public/integrations/wordpress/white-hat-cms-lite.php", import.meta.url), "utf8"),
    readFile(new URL("../docs/OPERATIONS.md", import.meta.url), "utf8"),
    readFile(new URL("../.openai/hosting.json", import.meta.url), "utf8"),
  ]);
  assert.match(migration, /CREATE TABLE `post_revisions`/);
  assert.match(migration, /CREATE TABLE `audit_events`/);
  assert.match(ai, /human review/i);
  assert.match(ai, /dispatchDistributionEvent/);
  assert.match(media, /R2Bucket/);
  assert.match(wordpress, /white_hat_cms_posts/);
  assert.match(operations, /Scheduled posts become public/);
  assert.match(hosting, /"r2": "MEDIA"/);
});
